# Generated by Django 4.1.2 on 2022-10-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(max_length=40)),
                ("topic", models.CharField(max_length=40)),
                ("question_text", models.TextField()),
                ("answer_a", models.TextField()),
                ("answer_b", models.TextField()),
                ("answer_c", models.TextField()),
                ("answer_d", models.TextField()),
                ("correct_answer", models.CharField(max_length=2)),
                ("comment", models.TextField()),
                ("image_url", models.URLField()),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
    ]
